global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'rabbitmq'

    scrape_interval: 5s
    scrape_timeout: 5s

    # metrics_path defaults to '/metrics'
    # optionally, we can use /metrics/per-object/
    # metrics_path: /metrics/per-object
    static_configs:
      - targets: ['localhost:15692','localhost:15693','localhost:15694']
    relabel_configs:
      - separator: ;
        source_labels:
          - rabbitmq_cluster
        target_label: rabbitmq_cluster
        replacement: localhost
        action: replace
      - separator: ;
        source_labels:
          - namespace
        target_label: namespace
        replacement: local
        action: replace

  - job_name: perf-test
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:8080','localhost:8081','localhost:8082','localhost:8083','localhost:8084','localhost:8085']
    relabel_configs:
      - separator: ;
        source_labels:
          - namespace
        target_label: namespace
        replacement: local
        action: replace

  - job_name: node-exporter
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9100']

